// Copyright 2018-2026 the Deno authors. MIT license.

#[cfg(not(feature = "disable"))]
mod shared;

fn main() {
  #[cfg(not(feature = "disable"))]
  {
    let o = std::path::PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    let cli_snapshot_path = o.join("CLI_SNAPSHOT.bin");
    let residual_path = o.join("EXTENSION_RESIDUAL_SOURCES.rs");
    create_cli_snapshot(cli_snapshot_path, residual_path);
  }
}

#[cfg(not(feature = "disable"))]
fn create_cli_snapshot(
  snapshot_path: std::path::PathBuf,
  residual_path: std::path::PathBuf,
) {
  use std::collections::HashSet;
  use std::io::Write;

  use deno_runtime::ops::bootstrap::SnapshotOptions;
  use deno_runtime::snapshot::LazyExtensionFileKind;

  let snapshot_options = SnapshotOptions {
    ts_version: shared::TS_VERSION.to_string(),
    v8_version: deno_runtime::deno_core::v8::VERSION_STRING,
    target: std::env::var("TARGET").unwrap(),
  };

  let output = deno_runtime::snapshot::create_runtime_snapshot(
    snapshot_path,
    snapshot_options,
    vec![],
  );

  let consumed: HashSet<&str> = output
    .consumed_lazy_specifiers
    .iter()
    .map(String::as_str)
    .collect();

  let mut residual_js: Vec<(&str, &std::path::Path)> = Vec::new();
  let mut residual_esm: Vec<(&str, &std::path::Path)> = Vec::new();
  for file in &output.lazy_extension_files {
    if consumed.contains(file.specifier.as_str()) {
      continue;
    }
    // Make sure we rebuild when residual sources change.
    #[allow(clippy::print_stdout, reason = "build script output")]
    {
      println!("cargo:rerun-if-changed={}", file.path.display());
    }
    let entry = (file.specifier.as_str(), file.path.as_path());
    match file.kind {
      LazyExtensionFileKind::Js => residual_js.push(entry),
      LazyExtensionFileKind::Esm => residual_esm.push(entry),
    }
  }

  let mut f = std::fs::File::create(&residual_path).unwrap();
  writeln!(
    f,
    "// Copyright 2018-2026 the Deno authors. MIT license.\n\
     // @generated by cli/snapshot/build.rs — do not edit.\n"
  )
  .unwrap();
  write_residual_table(&mut f, "RESIDUAL_LAZY_JS", &residual_js);
  write_residual_table(&mut f, "RESIDUAL_LAZY_ESM", &residual_esm);
}

#[cfg(not(feature = "disable"))]
fn write_residual_table(
  f: &mut std::fs::File,
  name: &str,
  entries: &[(&str, &std::path::Path)],
) {
  use std::io::Write;
  writeln!(f, "pub static {name}: &[(&str, &str)] = &[").unwrap();
  for (specifier, path) in entries {
    // The path comes from CARGO_MANIFEST_DIR-rooted concat! literals, so it is
    // already absolute and stable across the workspace.
    writeln!(f, "  ({specifier:?}, include_str!({path:?})),",).unwrap();
  }
  writeln!(f, "];\n").unwrap();
}
