// Copyright 2018-2026 the Deno authors. MIT license.

#[cfg(not(feature = "disable"))]
mod shared;

fn main() {
  // Trigger a snapshot rebuild whenever the import-graph instrumentation is
  // toggled (see libs/core/modules/import_graph.rs).
  #[allow(clippy::print_stdout, reason = "build script output")]
  {
    println!("cargo:rerun-if-env-changed=DENO_SNAPSHOT_IMPORT_GRAPH");
  }
  #[cfg(not(feature = "disable"))]
  {
    let o = std::path::PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    let cli_snapshot_path = o.join("CLI_SNAPSHOT.bin");
    let residual_path = o.join("EXTENSION_RESIDUAL_SOURCES.rs");
    create_cli_snapshot(cli_snapshot_path, residual_path);
  }
}

#[cfg(not(feature = "disable"))]
fn create_cli_snapshot(
  snapshot_path: std::path::PathBuf,
  residual_path: std::path::PathBuf,
) {
  use std::collections::HashSet;
  use std::io::Write;

  use deno_runtime::ops::bootstrap::SnapshotOptions;
  use deno_runtime::snapshot::LazyExtensionFileKind;

  let snapshot_options = SnapshotOptions {
    ts_version: shared::TS_VERSION.to_string(),
    v8_version: deno_runtime::deno_core::v8::VERSION_STRING,
    target: std::env::var("TARGET").unwrap(),
  };

  let output = deno_runtime::snapshot::create_runtime_snapshot(
    snapshot_path,
    snapshot_options,
    vec![],
  );

  let consumed: HashSet<&str> = output
    .consumed_lazy_specifiers
    .iter()
    .map(String::as_str)
    .collect();

  let out_dir = std::path::PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
  let residual_sources_dir = out_dir.join("residual_sources");
  std::fs::create_dir_all(&residual_sources_dir).unwrap();

  let mut residual_js: Vec<ResidualSource> = Vec::new();
  let mut residual_esm: Vec<ResidualSource> = Vec::new();
  for file in &output.lazy_extension_files {
    if consumed.contains(file.specifier.as_str()) {
      continue;
    }
    // Make sure we rebuild when residual sources change.
    #[allow(clippy::print_stdout, reason = "build script output")]
    {
      println!("cargo:rerun-if-changed={}", file.path.display());
    }
    // Both lazy_loaded_js (loadExtScript -> v8::Script::compile on raw
    // source) and lazy_loaded_esm (op_lazy_load_esm -> LazyEsmModuleLoader,
    // which returns the source unchanged) skip transpilation at runtime.
    // The snapshot path applies extension_transpiler for consumed files;
    // for residuals we have to pre-transpile here so the runtime gets
    // parseable JS rather than TypeScript syntax.
    let residual_source =
      build_residual_source(&residual_sources_dir, &file.specifier, &file.path);
    match file.kind {
      LazyExtensionFileKind::Js => residual_js.push(residual_source),
      LazyExtensionFileKind::Esm => residual_esm.push(residual_source),
    }
  }

  let mut f = std::fs::File::create(&residual_path).unwrap();
  writeln!(
    f,
    "// Copyright 2018-2026 the Deno authors. MIT license.\n\
     // @generated by cli/snapshot/build.rs - do not edit.\n"
  )
  .unwrap();
  // Both tables reference compressed files emitted under
  // $OUT_DIR/residual_sources/, so `include_bytes!` uses an OUT_DIR-rooted
  // concat! literal rather than a source-tree path.
  write_residual_table(&mut f, &out_dir, "RESIDUAL_LAZY_JS", &residual_js);
  write_residual_table(&mut f, &out_dir, "RESIDUAL_LAZY_ESM", &residual_esm);
}

#[cfg(not(feature = "disable"))]
struct ResidualSource {
  specifier: String,
  compressed_path: std::path::PathBuf,
  uncompressed_size: usize,
}

#[cfg(not(feature = "disable"))]
fn build_residual_source(
  out_dir: &std::path::Path,
  specifier: &str,
  src_path: &std::path::Path,
) -> ResidualSource {
  use deno_runtime::deno_core::ModuleCodeString;
  use deno_runtime::deno_core::ModuleName;
  use deno_runtime::transpile::maybe_transpile_source;

  let source = std::fs::read_to_string(src_path).unwrap_or_else(|e| {
    panic!(
      "failed to read residual lazy source {}: {e}",
      src_path.display()
    )
  });
  let (transpiled, _source_map) = maybe_transpile_source(
    ModuleName::from(specifier.to_string()),
    ModuleCodeString::from(source),
  )
  .unwrap_or_else(|e| {
    panic!("failed to transpile residual lazy source {specifier}: {e}")
  });

  // Sanitize the specifier into a filesystem-safe name. Specifiers look like
  // `ext:deno_node/https.ts`, which we want to round-trip into a unique file.
  let sanitized: String = specifier
    .chars()
    .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
    .collect();
  let compressed_path = out_dir.join(format!("{sanitized}.js.zst"));
  let compressed = zstd::bulk::compress(transpiled.as_bytes(), 19)
    .unwrap_or_else(|e| {
      panic!("failed to compress residual lazy source {specifier}: {e}")
    });
  std::fs::write(&compressed_path, compressed).unwrap();
  ResidualSource {
    specifier: specifier.to_string(),
    compressed_path,
    uncompressed_size: transpiled.len(),
  }
}

#[cfg(not(feature = "disable"))]
fn write_residual_table(
  f: &mut std::fs::File,
  out_dir: &std::path::Path,
  name: &str,
  entries: &[ResidualSource],
) {
  use std::io::Write;
  writeln!(
    f,
    "pub static {name}: &[(&str, deno_core::StaticSourceCode)] = &["
  )
  .unwrap();
  for entry in entries {
    let rel = entry.compressed_path.strip_prefix(out_dir).unwrap();
    writeln!(
      f,
      "  ({:?}, deno_core::StaticSourceCode::ZstdCompressed(deno_core::CompressedSourceCode {{ bytes: include_bytes!(concat!(env!(\"OUT_DIR\"), {:?})), uncompressed_size: {} }})),",
      entry.specifier,
      format!("/{}", rel.display()),
      entry.uncompressed_size,
    )
    .unwrap();
  }
  writeln!(f, "];\n").unwrap();
}
