// Copyright 2018-2026 the Deno authors. MIT license.

//! Generate `.deno/tsconfig.json` for use with stock TypeScript tooling
//! (tsc, tsgo).
//!
//! This module translates Deno's compiler options (from `deno.json`) into a
//! standard `tsconfig.json` that stock TypeScript understands. It also injects
//! Deno type definitions so that the `Deno` namespace and other Deno-specific
//! globals are available.

use std::path::Path;
use std::path::PathBuf;

use deno_core::serde_json;
use deno_core::serde_json::Map;
use deno_core::serde_json::Value;
use deno_core::serde_json::json;

use super::get_types_declaration_file_text;

const DENO_DIR_NAME: &str = ".deno";
const TSCONFIG_NAME: &str = "tsconfig.json";
const DENO_TYPES_DIR: &str = "types";
const DENO_TYPES_FILE: &str = "deno.d.ts";

/// Result of generating a tsconfig.json for stock TypeScript.
#[derive(Debug)]
pub struct GeneratedTsConfig {
  /// Path to the generated tsconfig.json (e.g., `<root>/.deno/tsconfig.json`).
  pub tsconfig_path: PathBuf,
  /// Path to the generated Deno type definitions file.
  pub _types_path: PathBuf,
}

/// Generate a `.deno/tsconfig.json` and Deno type definitions for use with
/// stock TypeScript tooling.
///
/// If the user has an existing `tsconfig.json` in the project root, the
/// generated config will extend it via `"extends"`.
///
/// `deno_compiler_options` should be the raw `compilerOptions` value from
/// `deno.json`, or `None` if there is no `deno.json`.
///
/// `deno_imports` should be the raw `imports` value from `deno.json`, used
/// to generate tsconfig `"paths"` for `npm:` specifiers.
///
/// `files` is the list of files to check. If empty, all project files are
/// included via `"include": ["../**/*"]`. If non-empty, only those files
/// are listed in the tsconfig `"files"` array.
pub fn generate_tsconfig(
  project_root: &Path,
  deno_compiler_options: Option<&Value>,
  deno_imports: Option<&Value>,
  files: &[String],
) -> Result<GeneratedTsConfig, std::io::Error> {
  let deno_dir = project_root.join(DENO_DIR_NAME);
  std::fs::create_dir_all(&deno_dir)?;

  // Write Deno type definitions
  let types_dir = deno_dir.join(DENO_TYPES_DIR);
  std::fs::create_dir_all(&types_dir)?;
  let types_path = types_dir.join(DENO_TYPES_FILE);
  write_deno_types(&types_path)?;

  // Build tsconfig
  let tsconfig = build_tsconfig(
    project_root,
    &types_path,
    deno_compiler_options,
    deno_imports,
    files,
  );

  let tsconfig_path = deno_dir.join(TSCONFIG_NAME);
  let content = serde_json::to_string_pretty(&tsconfig)
    .expect("failed to serialize tsconfig");
  std::fs::write(&tsconfig_path, content)?;

  Ok(GeneratedTsConfig {
    tsconfig_path,
    _types_path: types_path,
  })
}

/// Write the Deno type declarations to a `.d.ts` file.
fn write_deno_types(path: &Path) -> Result<(), std::io::Error> {
  let types_text = get_types_declaration_file_text();
  // Strip triple-slash reference directives that conflict with stock tsc
  let filtered: String = types_text
    .lines()
    .filter(|line| {
      let trimmed = line.trim();
      !(trimmed.starts_with("/// <reference no-default-lib")
        || trimmed.starts_with("/// <reference lib="))
    })
    .collect::<Vec<_>>()
    .join("\n");

  std::fs::write(
    path,
    format!(
      "// Auto-generated by Deno for stock TypeScript tooling.\n\
       // Do not edit — this file is regenerated as needed.\n\n\
       {filtered}"
    ),
  )
}

/// Build the tsconfig JSON object.
fn build_tsconfig(
  project_root: &Path,
  types_path: &Path,
  deno_compiler_options: Option<&Value>,
  deno_imports: Option<&Value>,
  check_files: &[String],
) -> Value {
  let mut compiler_options = base_compiler_options();

  // Merge user's deno.json compilerOptions (filtered to stock-tsc-compatible
  // options only)
  if let Some(user_opts) = deno_compiler_options {
    merge_deno_options(&mut compiler_options, user_opts);
  }

  // Generate "paths" for npm: and jsr: specifiers, then merge any
  // user-defined paths from deno.json compilerOptions on top.
  let mut specifier_paths = generate_npm_paths(project_root, deno_imports);
  let jsr_paths = generate_jsr_paths(project_root, deno_imports);
  specifier_paths.extend(jsr_paths);

  // Merge user-defined paths (from deno.json compilerOptions.paths) — these
  // take priority over generated specifier mappings so that explicit user
  // aliases win.
  if let Some(user_paths) = deno_compiler_options
    .and_then(|co| co.get("paths"))
    .and_then(|p| p.as_object())
  {
    for (key, value) in user_paths {
      specifier_paths.insert(key.clone(), value.clone());
    }
  }

  if !specifier_paths.is_empty() {
    compiler_options.insert("paths".to_string(), json!(specifier_paths));
  }

  // Add Deno types file path relative to .deno/ directory
  let deno_dir = project_root.join(DENO_DIR_NAME);
  let relative_types = pathdiff::diff_paths(types_path, &deno_dir)
    .unwrap_or_else(|| types_path.to_path_buf());
  let types_str = relative_types.to_string_lossy().to_string();

  // Build files list: always include Deno types, plus specified files
  let mut files_array = vec![json!(types_str)];

  let mut tsconfig = if check_files.is_empty() {
    // No specific files — check entire project
    json!({
      "compilerOptions": compiler_options,
      "include": ["../**/*"],
      "files": files_array,
      "exclude": ["../**/node_modules", "../.deno"],
    })
  } else {
    // Specific files requested — only check those
    // Paths are relative to .deno/ directory
    for file in check_files {
      let path = std::path::Path::new(file);
      let relative = if path.is_absolute() {
        pathdiff::diff_paths(path, &deno_dir)
          .unwrap_or_else(|| path.to_path_buf())
      } else {
        // Relative to project root, adjust for .deno/ location
        PathBuf::from("..").join(path)
      };
      files_array.push(json!(relative.to_string_lossy()));
    }
    json!({
      "compilerOptions": compiler_options,
      "files": files_array,
    })
  };

  // If user has a tsconfig.json, extend it
  let user_tsconfig = project_root.join("tsconfig.json");
  if user_tsconfig.exists() {
    tsconfig
      .as_object_mut()
      .unwrap()
      .insert("extends".to_string(), json!("../tsconfig.json"));
  }

  tsconfig
}

/// Generate tsconfig "paths" entries for npm: specifiers.
///
/// Scans `deno.json` `"imports"` for entries like:
///   `"express": "npm:express@4"` → `{ "npm:express": ["./node_modules/express"] }`
///
/// Also scans `node_modules/` directly for any installed packages and maps
/// `npm:<pkg>` to the local path.
fn generate_npm_paths(
  project_root: &Path,
  deno_imports: Option<&Value>,
) -> Map<String, Value> {
  let mut paths = Map::new();
  let node_modules = project_root.join("node_modules");

  // 1. From deno.json "imports" — map both the alias and the npm: specifier
  if let Some(imports) = deno_imports.and_then(|v| v.as_object()) {
    for (alias, target) in imports {
      let target_str = match target.as_str() {
        Some(s) => s,
        None => continue,
      };

      if let Some(pkg_name) = parse_npm_specifier(target_str) {
        // Paths are relative to tsconfig location (.deno/)
        let nm_path = format!("../node_modules/{pkg_name}");

        // Map the npm: specifier itself
        // e.g. "npm:express" → ["../node_modules/express"]
        let npm_key = format!("npm:{pkg_name}");
        paths
          .entry(npm_key.clone())
          .or_insert_with(|| json!([&nm_path]));
        paths
          .entry(format!("{npm_key}/*"))
          .or_insert_with(|| json!([format!("{nm_path}/*")]));

        // Also map the bare alias from deno.json imports
        // e.g. "chalk" → ["../node_modules/chalk"] (for `import x from "chalk"`)
        paths
          .entry(alias.clone())
          .or_insert_with(|| json!([&nm_path]));
        paths
          .entry(format!("{alias}/*"))
          .or_insert_with(|| json!([format!("{nm_path}/*")]));
      }
    }
  }

  // 2. Scan node_modules for any @scope/pkg or pkg directories and add
  //    npm:<pkg> mappings for them (catches packages not in deno.json imports)
  if node_modules.is_dir()
    && let Ok(entries) = std::fs::read_dir(&node_modules)
  {
    for entry in entries.flatten() {
      let name = entry.file_name();
      let name_str = name.to_string_lossy();

      if name_str.starts_with('.') || name_str.starts_with('@') {
        // Handle scoped packages
        if name_str.starts_with('@')
          && let Ok(scope_entries) = std::fs::read_dir(entry.path())
        {
          for scope_entry in scope_entries.flatten() {
            let pkg = scope_entry.file_name();
            let scoped_name = format!("{}/{}", name_str, pkg.to_string_lossy());
            let nm_path = format!("../node_modules/{scoped_name}");
            let npm_key = format!("npm:{scoped_name}");
            paths
              .entry(npm_key.clone())
              .or_insert_with(|| json!([&nm_path]));
            paths
              .entry(format!("{npm_key}/*"))
              .or_insert_with(|| json!([format!("{nm_path}/*")]));
          }
        }
        continue;
      }

      let nm_path = format!("../node_modules/{name_str}");
      let npm_key = format!("npm:{name_str}");
      paths
        .entry(npm_key.clone())
        .or_insert_with(|| json!([&nm_path]));
      paths
        .entry(format!("{npm_key}/*"))
        .or_insert_with(|| json!([format!("{nm_path}/*")]));
    }
  }

  paths
}

/// Parse an npm specifier like "npm:express@4" or "npm:@scope/pkg@1.2.3"
/// and return the package name (without version).
pub fn parse_npm_specifier(specifier: &str) -> Option<String> {
  let rest = specifier.strip_prefix("npm:")?;
  // Handle scoped packages: @scope/pkg@version
  if let Some(without_at) = rest.strip_prefix('@') {
    // Find the second @ (version separator) after the scope
    let after_scope = without_at.find('/')? + 1;
    let after_slash = &rest[after_scope + 1..];
    if let Some(version_at) = after_slash.find('@') {
      Some(rest[..after_scope + 1 + version_at].to_string())
    } else {
      Some(rest.to_string())
    }
  } else {
    // Unscoped: pkg@version
    if let Some(at_pos) = rest.find('@') {
      Some(rest[..at_pos].to_string())
    } else {
      Some(rest.to_string())
    }
  }
}

/// Generate tsconfig "paths" entries for jsr: specifiers.
///
/// JSR packages are available via npm compatibility at `npm.jsr.io` and install
/// to `node_modules/@jsr/<scope>__<name>`. Maps `jsr:@scope/name` to that path.
fn generate_jsr_paths(
  project_root: &Path,
  deno_imports: Option<&Value>,
) -> Map<String, Value> {
  let mut paths = Map::new();
  let node_modules = project_root.join("node_modules");

  // 1. From deno.json "imports" — map jsr: specifiers and bare aliases
  if let Some(imports) = deno_imports.and_then(|v| v.as_object()) {
    for (alias, target) in imports {
      let target_str = match target.as_str() {
        Some(s) => s,
        None => continue,
      };

      if let Some((scope, name, _version)) = parse_jsr_specifier(target_str) {
        // JSR npm compat uses @jsr/<scope>__<name>
        let jsr_npm_name =
          format!("{}__{}", scope.trim_start_matches('@'), name);
        let nm_path = format!("../node_modules/@jsr/{jsr_npm_name}");

        // Check if the package actually exists in node_modules
        let abs_path =
          project_root.join(format!("node_modules/@jsr/{jsr_npm_name}"));
        if !abs_path.exists() {
          continue;
        }

        // Resolve the types entry point from package.json exports
        let types_entry = resolve_jsr_types_entry(&abs_path)
          .unwrap_or_else(|| nm_path.to_string());

        // Map the jsr: specifier
        let jsr_key = format!("jsr:{scope}/{name}");
        paths
          .entry(jsr_key.clone())
          .or_insert_with(|| json!([&types_entry]));
        paths
          .entry(format!("{jsr_key}/*"))
          .or_insert_with(|| json!([format!("{nm_path}/*")]));

        // Also map the bare alias from deno.json imports
        // e.g. "@std/assert" → types entry (for `import x from "@std/assert"`)
        paths
          .entry(alias.clone())
          .or_insert_with(|| json!([&types_entry]));
        paths
          .entry(format!("{alias}/*"))
          .or_insert_with(|| json!([format!("{nm_path}/*")]));
      }
    }
  }

  // 2. Scan node_modules/@jsr/ for any installed jsr packages
  let jsr_dir = node_modules.join("@jsr");
  if jsr_dir.is_dir()
    && let Ok(entries) = std::fs::read_dir(&jsr_dir)
  {
    for entry in entries.flatten() {
      let name = entry.file_name();
      let name_str = name.to_string_lossy();
      if name_str.starts_with('.') {
        continue;
      }

      // Parse @jsr/scope__name back to jsr:@scope/name
      if let Some((scope, pkg)) = name_str.split_once("__") {
        let nm_path = format!("../node_modules/@jsr/{name_str}");
        let abs_pkg_path = node_modules.join("@jsr").join(name_str.as_ref());
        let types_entry = resolve_jsr_types_entry(&abs_pkg_path)
          .unwrap_or_else(|| nm_path.clone());
        let jsr_key = format!("jsr:@{scope}/{pkg}");
        paths
          .entry(jsr_key.clone())
          .or_insert_with(|| json!([&types_entry]));
        paths
          .entry(format!("{jsr_key}/*"))
          .or_insert_with(|| json!([format!("{nm_path}/*")]));
      }
    }
  }

  paths
}

/// Resolve the types entry point from a JSR package's package.json.
///
/// Reads the `"exports"` field and looks for `"."` → `"types"` condition.
/// Returns a path relative to `.deno/` (e.g., `../node_modules/@jsr/std__assert/_dist/mod.d.ts`).
fn resolve_jsr_types_entry(pkg_dir: &Path) -> Option<String> {
  let pkg_json_path = pkg_dir.join("package.json");
  let content = std::fs::read_to_string(&pkg_json_path).ok()?;
  let pkg_json: Value = serde_json::from_str(&content).ok()?;

  // Try exports["."]["types"]
  let types_path = pkg_json
    .get("exports")
    .and_then(|e| e.get("."))
    .and_then(|dot| dot.get("types"))
    .and_then(|t| t.as_str())
    .or_else(|| {
      // Fallback: top-level "types" field
      pkg_json.get("types").and_then(|t| t.as_str())
    })?;

  // Convert package-relative path to .deno/-relative path
  let pkg_name = pkg_dir.file_name()?.to_string_lossy();
  let parent_name = pkg_dir
    .parent()
    .and_then(|p| p.file_name())
    .map(|f| f.to_string_lossy())
    .unwrap_or_default();

  let types_path = types_path.strip_prefix("./").unwrap_or(types_path);

  if parent_name == "@jsr" {
    Some(format!("../node_modules/@jsr/{pkg_name}/{types_path}"))
  } else {
    Some(format!("../node_modules/{pkg_name}/{types_path}"))
  }
}

/// Parse a jsr specifier like "jsr:@std/assert@1" or "jsr:@scope/name@1.2.3"
/// and return (scope, name, version). E.g. ("@std", "assert", Some("1")).
/// The version is `None` if no `@version` suffix is present.
pub fn parse_jsr_specifier(
  specifier: &str,
) -> Option<(String, String, Option<String>)> {
  let rest = specifier.strip_prefix("jsr:")?;
  // JSR specifiers are always scoped: @scope/name@version
  if !rest.starts_with('@') {
    return None;
  }
  let slash_pos = rest.find('/')?;
  let scope = &rest[..slash_pos];
  let after_slash = &rest[slash_pos + 1..];
  let (name, version) = if let Some(at_pos) = after_slash.find('@') {
    (
      &after_slash[..at_pos],
      Some(after_slash[at_pos + 1..].to_string()),
    )
  } else {
    (after_slash, None)
  };
  Some((scope.to_string(), name.to_string(), version))
}

/// Base compiler options for stock tsc that approximate Deno's defaults.
fn base_compiler_options() -> Map<String, Value> {
  let obj = json!({
    // Deno defaults
    "strict": true,
    "noImplicitOverride": true,
    "allowJs": true,
    "checkJs": false,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,

    // Module settings for stock tsc
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "bundler",
    "moduleDetection": "force",

    // Allow .ts extensions in imports (TS 5.0+)
    "allowImportingTsExtensions": true,

    // Standard libs (Deno-specific libs like deno.window are replaced by
    // the injected Deno types file)
    "lib": ["esnext"],

    // Skip checking node_modules types for speed
    "skipLibCheck": true,
  });

  match obj {
    Value::Object(map) => map,
    _ => unreachable!(),
  }
}

/// Merge user's deno.json compilerOptions into the base, filtering to only
/// options that stock tsc understands.
fn merge_deno_options(base: &mut Map<String, Value>, user_opts: &Value) {
  let Some(user_map) = user_opts.as_object() else {
    return;
  };

  // Options from deno.json that map directly to tsconfig.json
  const PASSTHROUGH_OPTIONS: &[&str] = &[
    "allowUnreachableCode",
    "allowUnusedLabels",
    "checkJs",
    "emitDecoratorMetadata",
    "exactOptionalPropertyTypes",
    "experimentalDecorators",
    "isolatedDeclarations",
    "jsx",
    "jsxFactory",
    "jsxFragmentFactory",
    "jsxImportSource",
    "noErrorTruncation",
    "noFallthroughCasesInSwitch",
    "noImplicitAny",
    "noImplicitOverride",
    "noImplicitReturns",
    "noImplicitThis",
    "noPropertyAccessFromIndexSignature",
    "noUncheckedIndexedAccess",
    "noUnusedLocals",
    "noUnusedParameters",
    "rootDirs",
    "skipLibCheck",
    "strict",
    "strictBindCallApply",
    "strictBuiltinIteratorReturn",
    "strictFunctionTypes",
    "strictNullChecks",
    "strictPropertyInitialization",
    "useUnknownInCatchVariables",
    "verbatimModuleSyntax",
  ];

  for &key in PASSTHROUGH_OPTIONS {
    if let Some(value) = user_map.get(key) {
      base.insert(key.to_string(), value.clone());
    }
  }

  // Handle jsx: "precompile" -> "react-jsx" (stock tsc doesn't know precompile)
  if let Some(jsx) = user_map.get("jsx").and_then(|v| v.as_str())
    && jsx == "precompile"
  {
    base.insert("jsx".to_string(), json!("react-jsx"));
  }

  // Handle lib: merge with our base lib
  if let Some(user_lib) = user_map.get("lib").and_then(|v| v.as_array()) {
    let mut libs: Vec<Value> = vec![json!("esnext")];
    for lib in user_lib {
      if let Some(s) = lib.as_str() {
        // Skip Deno-specific libs that stock tsc doesn't know
        if !s.starts_with("deno.") && s != "esnext" {
          libs.push(lib.clone());
        }
      }
    }
    base.insert("lib".to_string(), Value::Array(libs));
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn test_base_compiler_options() {
    let opts = base_compiler_options();
    assert_eq!(opts.get("strict").unwrap(), &json!(true));
    assert_eq!(opts.get("target").unwrap(), &json!("esnext"));
    assert_eq!(opts.get("module").unwrap(), &json!("esnext"));
    assert_eq!(opts.get("noEmit").unwrap(), &json!(true));
  }

  #[test]
  fn test_merge_deno_options_passthrough() {
    let mut base = base_compiler_options();
    let user = json!({
      "strict": false,
      "jsx": "react-jsx",
      "jsxImportSource": "preact",
    });
    merge_deno_options(&mut base, &user);
    assert_eq!(base.get("strict").unwrap(), &json!(false));
    assert_eq!(base.get("jsx").unwrap(), &json!("react-jsx"));
    assert_eq!(base.get("jsxImportSource").unwrap(), &json!("preact"));
  }

  #[test]
  fn test_merge_deno_options_precompile_jsx() {
    let mut base = base_compiler_options();
    let user = json!({ "jsx": "precompile" });
    merge_deno_options(&mut base, &user);
    assert_eq!(base.get("jsx").unwrap(), &json!("react-jsx"));
  }

  #[test]
  fn test_merge_deno_options_filters_deno_libs() {
    let mut base = base_compiler_options();
    let user = json!({ "lib": ["deno.window", "dom", "esnext"] });
    merge_deno_options(&mut base, &user);
    let lib = base.get("lib").unwrap().as_array().unwrap();
    assert!(lib.contains(&json!("esnext")));
    assert!(lib.contains(&json!("dom")));
    assert!(!lib.iter().any(|v| v.as_str() == Some("deno.window")));
  }
}
