// Copyright 2018-2026 the Deno authors. MIT license.
import { core } from "ext:core/mod.js";
const {
  cachedDataVersionTag,
  getHeapCodeStatistics,
  getHeapSnapshot,
  getHeapSpaceStatistics,
  getHeapStatistics,
  setFlagsFromString,
  stopCoverage,
  takeCoverage,
  writeHeapSnapshot,
  serialize,
  deserialize,
  Serializer,
  Deserializer,
  DefaultSerializer,
  DefaultDeserializer,
} = core.loadExtScript("ext:deno_node/v8.ts");

export {
  cachedDataVersionTag,
  DefaultDeserializer,
  DefaultSerializer,
  deserialize,
  Deserializer,
  getHeapCodeStatistics,
  getHeapSnapshot,
  getHeapSpaceStatistics,
  getHeapStatistics,
  serialize,
  Serializer,
  setFlagsFromString,
  stopCoverage,
  takeCoverage,
  writeHeapSnapshot,
};
export default {
  cachedDataVersionTag,
  getHeapCodeStatistics,
  getHeapSnapshot,
  getHeapSpaceStatistics,
  getHeapStatistics,
  setFlagsFromString,
  stopCoverage,
  takeCoverage,
  writeHeapSnapshot,
  serialize,
  deserialize,
  Serializer,
  Deserializer,
  DefaultSerializer,
  DefaultDeserializer,
};
