// Copyright 2018-2026 the Deno authors. MIT license.
import { core } from "ext:core/mod.js";
const types = core.loadExtScript("ext:deno_node/internal/util/types.ts");
export const {
  isCryptoKey,
  isKeyObject,
  isArrayBufferView,
  isBigInt64Array,
  isBigUint64Array,
  isFloat16Array,
  isFloat32Array,
  isFloat64Array,
  isInt8Array,
  isInt16Array,
  isInt32Array,
  isUint8Array,
  isUint8ClampedArray,
  isUint16Array,
  isUint32Array,
  isAnyArrayBuffer,
  isArgumentsObject,
  isArrayBuffer,
  isAsyncFunction,
  isBigIntObject,
  isBooleanObject,
  isBoxedPrimitive,
  isDataView,
  isDate,
  isGeneratorFunction,
  isGeneratorObject,
  isMap,
  isMapIterator,
  isModuleNamespaceObject,
  isNativeError,
  isNumberObject,
  isPromise,
  isProxy,
  isRegExp,
  isSet,
  isSetIterator,
  isSharedArrayBuffer,
  isStringObject,
  isSymbolObject,
  isTypedArray,
  isWeakMap,
  isWeakSet,
} = types;
export default { ...types };
