// deno-fmt-ignore-file
// deno-lint-ignore-file

// Copyright Joyent and Node contributors. All rights reserved. MIT license.
// Taken from Node 18.12.1
// This file is automatically generated by `tools/node_compat/setup.ts`. Do not modify this file manually.

'use strict';
require('../common');
const vm = require('vm');
// Make this test OS-independent by overriding stdio getColorDepth().
process.stdout.getColorDepth = () => 8;
process.stderr.getColorDepth = () => 8;

console.log({ foo: 'bar' });
console.log('%s q', 'string');
console.log('%o with object format param', { foo: 'bar' });

console.log(
<<<<<<< HEAD
  new Error('test\n    at abc (../fixtures/node_modules/bar.js:4:4)\nfoobar'),
=======
  new Error('test\n    at abc (../fixtures/node_modules/bar.js:4:4)\nfoobar')
>>>>>>> 8c07f52a7 (1.38.4 (#21398))
);

try {
  require('../fixtures/node_modules/node_modules/bar.js');
} catch (err) {
  console.log(err);
}

vm.runInThisContext('console.log(new Error())');
