// Copyright 2018-2026 the Deno authors. MIT license.

// This file is auto-generated by tools/update_tsgo.ts
// DO NOT EDIT THIS FILE MANUALLY

pub struct Hashes {
  pub windows_x64: &'static str,
  pub windows_arm64: &'static str,
  pub macos_x64: &'static str,
  pub macos_arm64: &'static str,
  pub linux_x64: &'static str,
  pub linux_arm64: &'static str,
}

impl Hashes {
  pub const fn all(&self) -> [&'static str; 6] {
    [
      self.windows_x64,
      self.windows_arm64,
      self.macos_x64,
      self.macos_arm64,
      self.linux_x64,
      self.linux_arm64,
    ]
  }
}

pub const VERSION: &str = "0.1.16";
pub const DOWNLOAD_BASE_URL: &str =
  "https://github.com/denoland/typescript-go/releases/download/v0.1.16";
pub const HASHES: Hashes = Hashes {
  windows_x64: "sha256:749491a66c442e38fc61e8b261a08fcd312b7d886ddc80188fd0abb5b054eccd",
  windows_arm64: "sha256:cd21587880d05ff2ef87d30a9eea959d7a72a520d103a8f41df0f387d5adcc3a",
  macos_x64: "sha256:804efa966e1f303b8af37a72c1b866b0e8b41a539327bc2b8c5cac20bbc7e666",
  macos_arm64: "sha256:50600b58d59f046686bc2bb173431b86657e175dbf16b479ef25b450f5768f4f",
  linux_x64: "sha256:53eadc4030f3ef55a205fc4e819aaee10e84228638345fd225cb64f2539d28e5",
  linux_arm64: "sha256:aba1d0f24ee121403951e6c6d69688718971617159b357afc827aa94317dbb3d",
};

const _: () = {
  let sha256 = "sha256".as_bytes();

  let mut i = 0;
  let hashes = HASHES.all();

  while i < hashes.len() {
    let hash = hashes[i].as_bytes();
    let mut j = 0;

    while j < 6 {
      if hash[j] != sha256[j] {
        panic!("Hash algorithm is not sha256");
      }
      j += 1;
    }
    i += 1;
  }
};
