// Copyright 2018-2026 the Deno authors. MIT license.

// This file is auto-generated by tools/update_tsgo.ts
// DO NOT EDIT THIS FILE MANUALLY

pub struct Hashes {
  pub windows_x64: &'static str,
  pub windows_arm64: &'static str,
  pub macos_x64: &'static str,
  pub macos_arm64: &'static str,
  pub linux_x64: &'static str,
  pub linux_arm64: &'static str,
}

impl Hashes {
  pub const fn all(&self) -> [&'static str; 6] {
    [
      self.windows_x64,
      self.windows_arm64,
      self.macos_x64,
      self.macos_arm64,
      self.linux_x64,
      self.linux_arm64,
    ]
  }
}

pub const VERSION: &str = "0.1.19";
pub const DOWNLOAD_BASE_URL: &str =
  "https://github.com/denoland/typescript-go/releases/download/v0.1.19";
pub const HASHES: Hashes = Hashes {
  windows_x64: "sha256:92f2918378fc22d09ad6d1ceb1a88885653362b2906e344f84f82442048c6abf",
  windows_arm64: "sha256:c63c96f51b21bca8e7a54cc54c1094e664af3aecf214e92dab075067c45db903",
  macos_x64: "sha256:ec95648702510df312da4247b8825713b5bc71c59a7a2320980d3265287d6ad9",
  macos_arm64: "sha256:c4df21a13299eefb5b58d5728a08d9e3db3295f8d337915f9609935fb7afdfa1",
  linux_x64: "sha256:4089d04bf695155a0f7671c95b5b4ad68d2c424f88a924c52e5bc6b22735cec4",
  linux_arm64: "sha256:ff037938829703d743d9998fc62c62005ba177746bdcf13155a90facc4e873a2",
};

const _: () = {
  let sha256 = "sha256".as_bytes();

  let mut i = 0;
  let hashes = HASHES.all();

  while i < hashes.len() {
    let hash = hashes[i].as_bytes();
    let mut j = 0;

    while j < 6 {
      if hash[j] != sha256[j] {
        panic!("Hash algorithm is not sha256");
      }
      j += 1;
    }
    i += 1;
  }
};
