// Copyright 2018-2025 the Deno authors. MIT license.

// This file is auto-generated by tools/update_tsgo.ts
// DO NOT EDIT THIS FILE MANUALLY

pub struct Hashes {
  pub windows_x64: &'static str,
  pub macos_x64: &'static str,
  pub macos_arm64: &'static str,
  pub linux_x64: &'static str,
  pub linux_arm64: &'static str,
}

impl Hashes {
  pub const fn all(&self) -> [&'static str; 5] {
    [
      self.windows_x64,
      self.macos_x64,
      self.macos_arm64,
      self.linux_x64,
      self.linux_arm64,
    ]
  }
}

pub const VERSION: &str = "0.1.5";
pub const DOWNLOAD_BASE_URL: &str =
  "https://github.com/denoland/typescript-go/releases/download/v0.1.5";
pub const HASHES: Hashes = Hashes {
  windows_x64: "sha256:4ae059af1f0b895bb0c7463e3d28e59cbb3d8c23466fe2960e500f34df46ffa3",
  macos_x64: "sha256:fcb9b331077622e63f497917caca804f1890a97f8e7a19b88119e45b85c25961",
  macos_arm64: "sha256:65b7dd5ef27abf9c1dfaec9025fa714b4677c1634634b575bc14bdfc7c73e1a1",
  linux_x64: "sha256:806a07a8841e7c6332c09a62805c757ca7add9d1c20a067b9be31171733c1a06",
  linux_arm64: "sha256:0658171e9feb83c0e631751129f57b08bd86a7b9dc37c18a01aba0579492cc64",
};

const _: () = {
  let sha256 = "sha256".as_bytes();

  let mut i = 0;
  let hashes = HASHES.all();

  while i < hashes.len() {
    let hash = hashes[i].as_bytes();
    let mut j = 0;

    while j < 6 {
      if hash[j] != sha256[j] {
        panic!("Hash algorithm is not sha256");
      }
      j += 1;
    }
    i += 1;
  }
};
