// Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

// This module exports unstable Deno APIs.
((window) => {
  window.__bootstrap.denoNsUnstable = {
    signal: window.__bootstrap.signals.signal,
    signals: window.__bootstrap.signals.signals,
    Signal: window.__bootstrap.signals.Signal,
    SignalStream: window.__bootstrap.signals.SignalStream,
    transpileOnly: window.__bootstrap.compilerApi.transpileOnly,
    compile: window.__bootstrap.compilerApi.compile,
    bundle: window.__bootstrap.compilerApi.bundle,
    permissions: window.__bootstrap.permissions.permissions,
    Permissions: window.__bootstrap.permissions.Permissions,
    PermissionStatus: window.__bootstrap.permissions.PermissionStatus,
    openPlugin: window.__bootstrap.plugins.openPlugin,
    kill: window.__bootstrap.process.kill,
    setRaw: window.__bootstrap.tty.setRaw,
    consoleSize: window.__bootstrap.tty.consoleSize,
    DiagnosticCategory: window.__bootstrap.diagnostics.DiagnosticCategory,
    loadavg: window.__bootstrap.os.loadavg,
    hostname: window.__bootstrap.os.hostname,
    osRelease: window.__bootstrap.os.osRelease,
    applySourceMap: window.__bootstrap.errorStack.opApplySourceMap,
    formatDiagnostics: window.__bootstrap.errorStack.opFormatDiagnostics,
    shutdown: window.__bootstrap.net.shutdown,
    ShutdownMode: window.__bootstrap.net.ShutdownMode,
    listen: window.__bootstrap.netUnstable.listen,
    connect: window.__bootstrap.netUnstable.connect,
    listenDatagram: window.__bootstrap.netUnstable.listenDatagram,
    startTls: window.__bootstrap.tls.startTls,
    fstatSync: window.__bootstrap.fs.fstatSync,
    fstat: window.__bootstrap.fs.fstat,
    ftruncateSync: window.__bootstrap.fs.ftruncateSync,
    ftruncate: window.__bootstrap.fs.ftruncate,
    umask: window.__bootstrap.fs.umask,
    link: window.__bootstrap.fs.link,
    linkSync: window.__bootstrap.fs.linkSync,
    utime: window.__bootstrap.fs.utime,
    utimeSync: window.__bootstrap.fs.utimeSync,
    symlink: window.__bootstrap.fs.symlink,
    symlinkSync: window.__bootstrap.fs.symlinkSync,
    fdatasyncSync: window.__bootstrap.fs.fdatasyncSync,
    fdatasync: window.__bootstrap.fs.fdatasync,
    fsyncSync: window.__bootstrap.fs.fsyncSync,
    fsync: window.__bootstrap.fs.fsync,
  };
})(this);
