// Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

// This module exports unstable Deno APIs.
((window) => {
  window.__denoNsUnstable = {
    signal: window.__signals.signal,
    signals: window.__signals.signals,
    Signal: window.__signals.Signal,
    SignalStream: window.__signals.SignalStream,
    transpileOnly: window.__compilerApi.transpileOnly,
    compile: window.__compilerApi.compile,
    bundle: window.__compilerApi.bundle,
    permissions: window.__permissions.permissions,
    Permissions: window.__permissions.Permissions,
    PermissionStatus: window.__permissions.PermissionStatus,
    openPlugin: window.__plugins.openPlugin,
    kill: window.__process.kill,
    setRaw: window.__tty.setRaw,
    consoleSize: window.__tty.consoleSize,
    DiagnosticCategory: window.__diagnostics.DiagnosticCategory,
    loadavg: window.__os.loadavg,
    hostname: window.__os.hostname,
    osRelease: window.__os.osRelease,
    applySourceMap: window.__errorStack.opApplySourceMap,
    formatDiagnostics: window.__errorStack.opFormatDiagnostics,
    shutdown: window.__net.shutdown,
    ShutdownMode: window.__net.ShutdownMode,
    listen: window.__netUnstable.listen,
    connect: window.__netUnstable.connect,
    listenDatagram: window.__netUnstable.listenDatagram,
    startTls: window.__tls.startTls,
    fstatSync: window.__fs.fstatSync,
    fstat: window.__fs.fstat,
    ftruncateSync: window.__fs.ftruncateSync,
    ftruncate: window.__fs.ftruncate,
    umask: window.__fs.umask,
    link: window.__fs.link,
    linkSync: window.__fs.linkSync,
    utime: window.__fs.utime,
    utimeSync: window.__fs.utimeSync,
    symlink: window.__fs.symlink,
    symlinkSync: window.__fs.symlinkSync,
    fdatasyncSync: window.__fs.fdatasyncSync,
    fdatasync: window.__fs.fdatasync,
    fsyncSync: window.__fs.fsyncSync,
    fsync: window.__fs.fsync,
  };
})(this);
