#!/usr/bin/env -S deno run --check --allow-write=. --allow-read=../.. --lock=../../tools/deno.lock.json
// Copyright 2018-2026 the Deno authors. MIT license.

// Generates bump_crate_version.yml with the crate list derived from the workspace.

import { parse as parseToml } from "jsr:@std/toml@1";

const HEADER =
  "# GENERATED BY ./bump_crate_version.generate.ts -- DO NOT DIRECTLY EDIT";

interface CargoToml {
  workspace?: {
    members?: string[];
  };
  package?: {
    name?: string;
    version?: string;
  };
}

// Skip test crates and examples that aren't published
const excludedPrefixes = [
  "tests/",
  "libs/core/examples/",
  "libs/ops/compile_test_runner",
];

function resolvePublishableCrates(): string[] {
  const rootCargoToml = parseToml(
    Deno.readTextFileSync(new URL("../../Cargo.toml", import.meta.url)),
  ) as CargoToml;

  const members = rootCargoToml.workspace?.members ?? [];
  const crates: string[] = [];

  for (const member of members) {
    if (excludedPrefixes.some((p) => member.startsWith(p))) {
      continue;
    }
    try {
      const cargoToml = parseToml(
        Deno.readTextFileSync(
          new URL(`../../${member}/Cargo.toml`, import.meta.url),
        ),
      ) as CargoToml;
      const name = cargoToml.package?.name;
      const version = cargoToml.package?.version;
      if (name && version && version !== "0.0.0") {
        crates.push(name);
      }
    } catch {
      // skip members whose Cargo.toml can't be read
    }
  }

  crates.sort();
  return crates;
}

export function generate(): string {
  const crates = resolvePublishableCrates();
  const crateOptions = crates.map((c) => `          - ${c}`).join("\n");

  return `${HEADER}
name: bump_crate_version

on:
  workflow_dispatch:
    inputs:
      crate:
        description: "Crate to bump"
        type: choice
        required: true
        options:
${crateOptions}
      bumpKind:
        description: "Kind of version bump"
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
        required: true

jobs:
  bump:
    name: bump crate version
    runs-on: ubuntu-24.04
    timeout-minutes: 90

    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
      RUSTC_FORCE_INCREMENTAL: 1

    steps:
      - name: Configure git
        run: |
          git config --global core.symlinks true
          git config --global fetch.parallel 32

      - name: Clone repository
        uses: actions/checkout@v6
        with:
          token: \${{ secrets.DENOBOT_PAT }}
          submodules: recursive

      - uses: dsherret/rust-toolchain-file@v1

      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Bump \${{ github.event.inputs.crate }} (\${{ github.event.inputs.bumpKind }})
        run: ./tools/release/bump_single_crate_version.ts \${{ github.event.inputs.crate }} \${{ github.event.inputs.bumpKind }}

      - name: Create PR
        env:
          GH_TOKEN: \${{ secrets.DENOBOT_PAT }}
        run: |
          git config user.email "\${{ github.actor }}@users.noreply.github.com"
          git config user.name "\${{ github.actor }}"

          BRANCH_NAME="bump/\${{ github.event.inputs.crate }}_\${{ github.event.inputs.bumpKind }}"
          git checkout -b "\$BRANCH_NAME"
          git add .
          git commit -m "chore: bump \${{ github.event.inputs.crate }} (\${{ github.event.inputs.bumpKind }})"
          git push -u origin HEAD

          gh pr create \\
            --title "chore: bump \${{ github.event.inputs.crate }} (\${{ github.event.inputs.bumpKind }})" \\
            --body "Bumped \\\`\${{ github.event.inputs.crate }}\\\` version (\${{ github.event.inputs.bumpKind }})."
`;
}

export const CI_YML_URL = new URL(
  "./bump_crate_version.yml",
  import.meta.url,
);

if (import.meta.main) {
  Deno.writeTextFileSync(CI_YML_URL, generate());
  console.log("Generated bump_crate_version.yml");
}
