name: create_prerelease_tag

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tag:
    name: create prerelease tag
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Configure git
        run: |
          git config --global core.symlinks true
          git config --global fetch.parallel 32

      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.DENOBOT_PAT }}

      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Create release tag and check forward commit to main
        env:
          GITHUB_TOKEN: ${{ secrets.DENOBOT_PAT }}
          GH_WORKFLOW_ACTOR: ${{ github.actor }}
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          ./tools/release/04_post_publish.ts
